source 'git@github.com:CocoaPods/Specs.git' 
target 'IOSScanner' do
    platform :ios, '7.0' 
    pod 'WeexSDK', '0.13.0'   ## 建议使用WeexSDK新版本
    pod 'AFNetworking','~>3.1.0'
    pod  'WXDevtool',   '0.7.0'

end
